# Generated by Django 5.1.3 on 2024-11-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_appassets"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nationality",
            field=models.TextField(blank=True, null=True),
        ),
    ]
