# Generated by Django 5.1.3 on 2024-11-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_nationality"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
