# Generated by Django 5.1.3 on 2024-11-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="appassets",
            name="movies_banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AddField(
            model_name="appassets",
            name="tickets_banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
