# Generated by Django 5.1.3 on 2024-11-28 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movies_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movies",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="release_date",
            field=models.DateField(),
        ),
    ]
