# Generated by Django 5.1.3 on 2024-11-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movies_date_added_movies_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
