# Generated by Django 5.1.3 on 2024-11-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movies_date_added_alter_movies_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
