# Generated by Django 5.1.3 on 2024-11-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movies_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="movie_genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.genre",
            ),
        ),
    ]
