# Generated by Django 5.1.3 on 2024-11-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movies_movie_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EN", "English"),
                    ("NP", "Nepali"),
                    ("ES", "Spanish"),
                    ("HI", "Hindi"),
                    ("OT", "Others"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
