# Generated by Django 5.1.3 on 2024-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_movies_movie_poster_link_movies_trailer_embed_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EN", "English"),
                    ("NP", "Nepali"),
                    ("ES", "Spanish"),
                    ("HI", "Hindi"),
                    ("KO", "Korean"),
                    ("JP", "Japanese"),
                    ("CH", "Chinese"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
