# Generated by Django 5.1.3 on 2024-12-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_rename_movie_genre_genre_genre_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movies",
            old_name="movie_genre",
            new_name="genre_name",
        ),
    ]
